{{- $root := . -}}
{{- range .Values.dnsServers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.serviceName }}-tcp-{{ .server }}
  namespace: default
spec:
  ports:
    - port: 53
      protocol: TCP
  selector:
    app: {{ $root.Values.serviceName }}-{{ .server }}
  clusterIP: {{ .ip }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.serviceName }}-udp-{{ .server }}
  namespace: default
spec:
  ports:
    - port: 53
      protocol: UDP
  selector:
    app: {{ $root.Values.serviceName }}-{{ .server }}
  clusterIP: {{ .ip }}
---
{{- end }}  