{{- $root := . -}}
{{- range .Values.dnsServers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.serviceName }}-tcp-{{ .server }}
  namespace: default
spec:
  ports:
    - port: 53
      protocol: TCP
      name: dns-tcp-{{ .server }}
    - port: 53
      protocol: UDP
      name: dns-udp-{{ .server }}
    - port: 8081
      protocol: TCP
      name: ui-tcp-{{ .server }}
  selector:
    app: {{ $root.Values.serviceName }}-{{ .server }}
  clusterIP: {{ .ip }}
---
{{- end }}  