{{- $root := . -}}
{{- range .Values.dnsServers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.serviceName }}-int-{{ .server }}
  namespace: default
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: {{ $root.Values.serviceName }}-{{ .server }}
  clusterIP: {{ .ip }}
---
{{- end }}  